name: Reminder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and run Go code
        run: go run src/main.go
        env:
          GOOGLE_SHEETS_API_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_API_CREDENTIALS }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
